spring: #全局配置
  datasource:
    url: jdbc:mysql://47.93.220.219:3306/blog?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wzc
    password: 954845887
  thymeleaf:
    cache: false
    encoding: UTF-8
  profiles:
    active: dev
  redis:
    host: 47.93.220.219  #配置redis的主机地址，需要修改成自己的
    database: 15
    port: 6379
    password: 954845887
    lettuce:
      pool:
        max-active: 50 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool 的状态为exhausted(耗尽)
        max-idle: 20 # 连接池中的最大空闲连接，默认值也是8。
        min-idle: 5  # 连接池中的最小空闲连接，默认值也是0。
        # max-wait: 5 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接 抛出JedisConnectionException

comment.avatar: /images/avatar.jpg


pagehelper: #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

mybatis:
  type-aliases-package: com.wzc.blog.pojo
  mapper-locations: classpath:mapper/*.xml   #ָ指定myBatis的核心配置文件与Mapper映射文件

jwt:
  secret: blog@Login(Auth}*^31)&wzc% # 登录校验的密钥
  pubKeyPath: rsa.pub # 公钥地址
  priKeyPath: rsa.pri # 私钥地址
  expire: 60 # 过期时间,单位分钟
  cookie-name: user
  cookie-max-age: 64800

# 雪花id
snowflake:
  workerId: 1L
  datacenterId: 1L

logging:
  level:
    root: info
    com.wzc: debug
  file:
    name: blog.log
  config: classpath:log4j-spring.xml
#  /root/blog/blog

server:
  port: 8091