spring: #全局配置
  datasource:
    url: jdbc:mysql://47.93.220.219:3306/blog?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wzc
    password: 954845887
  thymeleaf:
    cache: false
    encoding: UTF-8
  profiles:
    active: dev

comment.avatar: /images/avatar.jpg


pagehelper: #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

mybatis:
  type-aliases-package: com.wzc.blog.pojo   #设置别名
  mapper-locations: classpath:mapper/*.xml   #ָ指定myBatis的核心配置文件与Mapper映射文件

jwt:
  secret: blog@Login(Auth}*^31)&wzc% # 登录校验的密钥
  pubKeyPath: rsa.pub # 公钥地址
  priKeyPath: rsa.pri # 私钥地址
  expire: 60 # 过期时间,单位分钟
  cookie-name: user
  cookie-max-age: 64800
logging:
  level:
    root: info
    com.wzc: debug
  file:
    name: blog.log
#  /root/blog/blog
server:
  port: 8091